FUC! 
The top line does not work
***
        try {
            const response = await fetch('https://www.gnu.org/home.en.html');
            console.log(response)
            // if (!response.ok) {
            //     throw new Error('Failed to fetch website');
            // }
            await interaction.reply("hello")
            // const htmlContent = await response.text();
            // console.log(htmlContent)
            // await interaction.reply(htmlContent);
        } catch (error) {
            console.error('Error fetching website:', error);
            // await interaction.reply('Failed to fetch website');
        }
***


BUT THE BOTTOM LINE WORKS, WTF!!!!! WHY!!!!!:

***
try{
    const response = await fetch('https://www.gnu.org/home.en.html');
    console.log(response)
    await interaction.reply("Website successfully visited")
} catch (error){
    console.error ("Error; ", error)
}
***


WTF, i found the issue:
 you cannot have comments in the try block (i guess also not in the error block). like WHY!!!!!!!
 it is really weird. adding and then removing a blank line makes the line work. ANd yes, that bot 'parser'
 or interpreter does not like comments is confirmed.
 

positive news is that whatever 'working configuration' there is, it keeps working when the same bot 'process' is running.


-----using this file as garbage bin---
        url = 'https://www.gnu.org/home.en.html'
        const response = await axios.get(url);
        // console.log(`Content of ${url}: ${response.data}`)
        headers = response.headers
        // console.log(headers)
		// await interaction.reply(response.headers);
        try {
            const response = await axios.get('https://www.gnu.org/home.en.html');
            await interaction.reply(`Fetched data: ${response.data}`);
        } catch (error) {
            console.error('Error fetching data:', error);
            await interaction.reply('Error fetching data');
        }
        output = ""
        fetch('https://www.gnu.org/home.en.html')
            .then(response => {
                // Check if response is successful (status code in the range 200-299)
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                // Parse response body as text
                return response.text();
            })
            .then(html => {
                // Handle the fetched HTML content
                console.log(html);
                await interaction.reply(html)
                // You can use a library like cheerio to parse HTML if needed
            })
            .catch(error => {
                // Handle errors
                console.error('Error fetching data:', error);
            });
        await interaction.reply(output)
        await interaction.reply('website fetched')
        try {
            const response = await fetch('https://www.gnu.org/home.en.html');
            console.log(response)
            // if (!response.ok) {
            //     throw new Error('Failed to fetch website');
            // }
            await interaction.reply("hello")
            // const htmlContent = await response.text();
            // console.log(htmlContent)
            // await interaction.reply(htmlContent);
        } catch (error) {
            console.error('Error fetching website:', error);
            // await interaction.reply('Failed to fetch website');
        }



-------temp garbage----
const cheerio = require('cheerio');
const $ = cheerio.load(html);
$('p').each((index, element) => {
                console.log('got here')
            });

note: having variables that is unused can also cause the program to collapse


----
   const html = await response.text();
            console.log(html)

 const header = response.headers;
            console.log(header)

=------temp garbage from openai project----
 // const { options } = interaction;
        // const text = options.getString('text');


------hello
const url = ;

-----
the code that uses passed in text


const { SlashCommandBuilder } = require('discord.js');
const axios = require('axios');


async function callOpenAI(text) {
    const url = 'https://api.openai.com/v1/chat/completions'
    const headers = {
        "Content-Type": "application/json",
        "Authorization": "Bearer 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",
    };

    console.log("executed")
    
    try {
        const response = await axios.post(url, {
            model: "gpt-3.5-turbo",
            messages: [{ role: "user", content: "Say this is a test!" }],
            temperature: 0.7
        }, { headers });
    
        return response.data;
    } catch (error) {
        console.error('Error calling OpenAI API:', error);
        return 'An error occurred while processing your request.';
    }
}

module.exports = {
	data: new SlashCommandBuilder()
		.setName('openaiapi')
		.setDescription('calls gpt4 for chat completion'),
	async execute(interaction) {
        const text = 'efficient sorting algorithms'
        
        const response = await callOpenAI(text);
        console.log(response)
        await interaction.reply("hello");
      
	},
};


-----
const out = await callOpenAI();
        const message = out.choices[0].message.content
        console.log(out)
        await interaction.reply("hello");